"""Optimal execution and transaction cost analysis."""

from __future__ import annotations

from .benchmarks import Benchmark, Score, benchmark_price, order_window, score_order
from .calibration import (
    Estimate,
    ExecutionSample,
    LinearTemporaryFit,
    PowerLawFit,
    fit_linear_temporary,
    fit_permanent,
    fit_power_law,
    samples_from_orders,
)
from .costs import cost_bps, cost_currency, cost_per_share
from .exceptions import (
    CalibrationError,
    ConvergenceError,
    IdentifiabilityWarning,
    InsufficientDataError,
    NoVolumeError,
    SlippageError,
    ValidationError,
)
from .execution import (
    ExecutionProblem,
    HalfLifeSensitivity,
    Trajectory,
    closed_form_moments,
    efficient_frontier,
    half_life_sensitivity,
    linear_trajectory,
    optimal_trajectory,
    schedule_moments,
    trajectory_from_trades,
)
from .impact import (
    ImpactModel,
    LinearImpact,
    PowerLawImpact,
    ScheduleCost,
    SquareRootLaw,
    schedule_cost,
    uniform_schedule,
)
from .scheduling import SchedulePlan, participation_caps, schedule_objective, solve_schedule
from .series import BarSeries
from .shortfall import (
    DelayBasis,
    FillAttribution,
    ShortfallBreakdown,
    attribute_fills,
    implementation_shortfall,
    participation_rate,
    shortfall_from_market,
)
from .simulate import CostDistribution, simulate_costs, simulate_prices
from .types import Bar, Fill, Order, Side
from .volume import (
    PovSchedule,
    VolumeProfile,
    estimate_profile,
    pov_schedule,
    round_to_lots,
    twap_schedule,
    vwap_schedule,
)

__version__ = "0.1.0"

__all__ = [
    "Bar",
    "BarSeries",
    "Benchmark",
    "CalibrationError",
    "ConvergenceError",
    "CostDistribution",
    "DelayBasis",
    "Estimate",
    "ExecutionProblem",
    "ExecutionSample",
    "Fill",
    "FillAttribution",
    "HalfLifeSensitivity",
    "IdentifiabilityWarning",
    "ImpactModel",
    "InsufficientDataError",
    "LinearImpact",
    "LinearTemporaryFit",
    "NoVolumeError",
    "Order",
    "PovSchedule",
    "PowerLawFit",
    "PowerLawImpact",
    "ScheduleCost",
    "SchedulePlan",
    "Score",
    "ShortfallBreakdown",
    "Side",
    "SlippageError",
    "SquareRootLaw",
    "Trajectory",
    "ValidationError",
    "VolumeProfile",
    "__version__",
    "attribute_fills",
    "benchmark_price",
    "closed_form_moments",
    "cost_bps",
    "cost_currency",
    "cost_per_share",
    "efficient_frontier",
    "estimate_profile",
    "fit_linear_temporary",
    "fit_permanent",
    "fit_power_law",
    "half_life_sensitivity",
    "implementation_shortfall",
    "linear_trajectory",
    "optimal_trajectory",
    "order_window",
    "participation_caps",
    "participation_rate",
    "pov_schedule",
    "round_to_lots",
    "samples_from_orders",
    "schedule_cost",
    "schedule_moments",
    "schedule_objective",
    "score_order",
    "shortfall_from_market",
    "simulate_costs",
    "simulate_prices",
    "solve_schedule",
    "trajectory_from_trades",
    "twap_schedule",
    "uniform_schedule",
    "vwap_schedule",
]
